"""Create GIN trigram indices for food search.

IMPORTANT: This migration's `down_revision` must be updated to the autogenerated
initial-schema revision ID (typically starts with a random string like `abc123`).
After running `alembic revision --autogenerate -m "initial schema"`, edit this
file's `down_revision` to match.

Revision ID: 003
Revises: <autogen-initial-schema-id>
Create Date: 2026-04-22

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "003"
# TODO(dev): update this to match the autogenerated initial-schema revision id.
down_revision: str | Sequence[str] | None = "002_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_foods_name_trgm "
        "ON foods USING gin (name gin_trgm_ops)"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_food_aliases_alias_trgm "
        "ON food_aliases USING gin (alias gin_trgm_ops)"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_food_aliases_alias_trgm")
    op.execute("DROP INDEX IF EXISTS ix_foods_name_trgm")
